services:
  spending-tracker:
    image: spending-tracker:latest
    container_name: ${CONTAINER_NAME:-spending-tracker}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ${DATA_DIR:-./data/uploads}:/app/uploads
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - HOSTNAME=${HOSTNAME:-0.0.0.0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30}s
      timeout: ${HEALTH_CHECK_TIMEOUT:-10}s
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-512m}
          cpus: '${CPU_LIMIT:-1.0}'
        reservations:
          memory: ${MEMORY_RESERVATION:-256m}
          cpus: '${CPU_RESERVATION:-0.5}'
    networks:
      - spending-tracker-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/cache:noexec,nosuid,size=50m

networks:
  spending-tracker-network:
    name: ${NETWORK_NAME:-spending-tracker-network}
    driver: ${NETWORK_DRIVER:-bridge}

volumes:
  uploads:
    driver: local